### PR TITLE
Improved multi-robot rendering capabilities

### PR DESCRIPTION
**Pull request by GustavoSilvera**
- Improved capability to render multiple robot algorithms on the same episode
- Added `run_multi_robot.sh` script to automate running several different robot algorithms on the same episode
- Fixed the `environment.yml` to install the barebones requirements for creating a conda installation
- Updated documentation to `docs/`
- Updated some params allowing for more consistent rendering
- Improved performance of legend plotting

### CODE REVIEW

**Review by ajdroid — COMMENTED** [review]
Are `JoystickSocialForce` and others included with this repo? Or if you don't have the baselines do they just raise a NotImplementedError?

**Comment by GustavoSilvera** [comment]
This pr does not include any joysticks besides what was already included (sampling & random planner). So yes, this will raise a `NotImplementedError` for other joysticks unless they get installed.

**Comment by GustavoSilvera** [comment]
Putting this PR on hold for a while. It improves some non-critical functionality for users and we want to run more tests before merging.

**Comment by GustavoSilvera** [comment]
*Bump*ing this PR. It will probably help with a lot of the installation issues from earlier.

@ajdroid wanna run the tests and make sure it looks good

**Comment by ajdroid** [comment]
Needed to change the `opencv` install version to `4.2.*` in `multi-robot-rendering/environment.yml`

Had an issue with the pyopenGL similar to: https://github.com/MPI-IS/mesh/issues/23
>  File "/usr/lib/python3/dist-packages/OpenGL/raw/GLES2/_types.py", line 5, in <module>
    _error_checker = _ErrorChecker( _p, _p.GLES2.glGetError )
    
Was able to bypass by setting `_error_checker=None` in that file. Can you reproduce @GustavoSilvera ?

After this workaround

image

**Comment by GustavoSilvera** [comment]
I can confirm that upgrading the opencv to `4.2.*` still maintains fully-functional unit tests. But I did not need to perform the `_error_checker=None` workaround. 

I also recently added some changes to address #17 and #18 by simplifying the installation process

**Pull request merged**
